set -e, fixes of exit codes

diff --git a/lib/optparse b/lib/optparse
--- a/lib/optparse
+++ b/lib/optparse
@@ -57,12 +57,12 @@ ARG_LIM=$1; }
 
 
 function add_info {
-if [ $# -ge 2 ]; then echo 'ERROR: add_info acts on a single text string'; exit; fi 
+if [ $# -ge 2 ]; then echo 'ERROR: add_info acts on a single text string'; exit 1; fi
 HELP_INFO=$1; }
 
 
 function add_example {
-if [ $# -ge 2 ]; then echo 'ERROR: add_example acts on a single text string'; exit; fi 
+if [ $# -ge 2 ]; then echo 'ERROR: add_example acts on a single text string'; exit 1; fi
 HELP_EXAMPLE=$1
  }
 
@@ -74,7 +74,7 @@ HELP_EXAMPLE=$1
 
 
 function add_flag {
-if [ $# == 0 ]; then echo 'ERROR: add_flag requires at least one argument'; exit; fi  
+if [ $# == 0 ]; then echo 'ERROR: add_flag requires at least one argument'; exit 1; fi
 if [ $# == 1 ]; then 
 	local SHRT='None' 
 	local DEF='False' 
@@ -98,7 +98,7 @@ if [ $# == 2 ]; then
 			local DEF='False' 
 		else
 			echo 'ERROR: Wrong Flag Input '"$2"
-			exit 
+			exit 1
 		fi 
 	fi 
 fi 
@@ -107,13 +107,13 @@ if [ $# -ge 3 ]; then
 		local SHRT=$(echo $2 | sed 's/.\(.\).*/\1/g')
 	else
 		echo 'Error: Incorrect Short Form Input: '"$2"
-		exit 
+		exit 1
 	fi 
 	if [ $3 == 'True' ] || [ $3 == 'False' ]; then 
 		local DEF=$3
 	else
 		echo 'Error: Flag default can only be True or False '"$3"
-		exit 
+		exit 1
 	fi
 fi 
 FLAG_DEF[$FLAGS_ADDED]=$DEF
@@ -133,7 +133,7 @@ else FLAG_DES[$FLAGS_ADDED]='None'
 fi 
 if [ $# -ge 5 ]; then 
 echo 'Error: add_flag takes at most 4 paramters'
-exit 
+exit 1
 fi 
 }
 
@@ -143,7 +143,7 @@ fi
 	
 
 function add_option { 
-if [ $# == 0 ]; then echo 'ERROR: add_option requires at least one argument'; exit; fi  
+if [ $# == 0 ]; then echo 'ERROR: add_option requires at least one argument'; exit 1; fi
 if [ $# == 1 ]; then 
 	local SHRT='None' 
 	local DEF='None' 
@@ -169,7 +169,7 @@ if [ $# -ge 3 ]; then
 		local SHRT=$(echo $2 | sed 's/.\(.\).*/\1/g')
 	else
 		echo 'Error: Incorrect Short Form Input: '"$2"
-		exit 
+		exit 1
 	fi 
 	local DEF=$3
 fi 
@@ -190,7 +190,7 @@ else OPT_DES[$OPTS_ADDED]='None'
 fi 
 if [ $# -ge 5 ]; then 
 echo 'Error: add_option takes at most 4 paramters'
-exit 
+exit 1
 fi 
 }
 
@@ -262,7 +262,7 @@ function usage {
 			j=`expr $j + 1`
 			done
 	fi 
-	exit 
+	exit 1
 }
 
 hput() {
@@ -283,8 +283,8 @@ function parseargs {
 	Argc=0
 	if [ $# == 0 ]; then 
 		echo 'Empty args'
-		usage 
-		exit 
+		usage
+		exit 1
 		fi 
 	until [ -z "$1" ]  # Until all parameters used up . . .
 	do
@@ -297,7 +297,7 @@ function parseargs {
 				echo 'ERROR: An argument is required for this option: '"$VAR" 
 				echo ''
 				usage 
-				exit 
+				exit 1
 			else 
 				eval $VAR=$1
 				ARG=
@@ -318,7 +318,7 @@ function parseargs {
 						echo 'ERROR: The long form option: '"$1"' is undeclared';
 						echo '' 
 						usage  
-						exit 
+						exit 1
 					fi
 				else 
 					CURRENT_OPTION=$(echo `hget $(echo $1 | sed 's/.\(.*\)/\1/g')`)
@@ -326,7 +326,7 @@ function parseargs {
 						echo 'ERROR: The short form option: '"$1"' is undeclared'
 						echo '' 
 						usage 
-						exit 
+						exit 1
 					fi  
 				fi			
 				if [ $(echo `hget "$CURRENT_OPTION""TYPE"`) == Flag ]; then
@@ -348,7 +348,7 @@ function parseargs {
 		VAR=$(echo $CURRENT_OPTION | sed 's/..\(.*\)/\1/g') 
 		echo 'ERROR: An argument is required for this option: '"$VAR" 
 		usage 
-		exit 
+		exit 1
 	fi 
 
 	if [ -z != $ARG_LIM ]; 
@@ -358,7 +358,7 @@ function parseargs {
 			echo 'ERROR: Positional Arguments Exceed Maximum Limit ('"$ARG_LIM"')' 
 			echo '' 
 			usage 
-			exit
+			exit 1
 		fi 
    	fi 
 }
